# Generated by Django 3.2.4 on 2021-06-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mydatabase", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homeworkresult",
            name="author",
        ),
        migrations.AddField(
            model_name="homeworkresult",
            name="author",
            field=models.ManyToManyField(to="mydatabase.Student"),
        ),
        migrations.RemoveField(
            model_name="homeworkresult",
            name="homework",
        ),
        migrations.AddField(
            model_name="homeworkresult",
            name="homework",
            field=models.ManyToManyField(to="mydatabase.Homework"),
        ),
    ]
