# Generated by Django 3.2.4 on 2021-06-15 16:28
import datetime
from datetime import timedelta

from django.db import migrations


def create_objects(apps, schema_editor):
    Homework = apps.get_model("mydatabase", "Homework")
    Student = apps.get_model("mydatabase", "Student")
    Teacher = apps.get_model("mydatabase", "Teacher")
    HomeworkResult = apps.get_model("mydatabase", "HomeworkResult")
    delta = timedelta(days=3)
    d = datetime.datetime(2021, 6, 15, 12, 30, 10)
    hw = Homework(text="Do your homework, dude", deadline=delta, created_date=d)
    hw.save()
    st = Student(first_name="Alex", last_name="Plahotnik")
    st.save()
    te = Teacher(first_name="Ivan", last_name="Petrov")
    te.save()
    hr = HomeworkResult(solution="That is brilliant!")
    hr.save()
    hr.homework.add(hw)
    hr.author.add(st)


class Migration(migrations.Migration):

    dependencies = [
        ("mydatabase", "0002_auto_20210615_1415"),
    ]

    operations = [migrations.RunPython(create_objects)]
